CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_KEYBOARD_NAME="Sweep"

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=0
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# disable BLE on peripheral
# NOTE: keep default (=y) if want to pairing BLE host on split central, or wireless dongle
CONFIG_ZMK_BLE=y

# disable default split transport on central and peripheral
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_WIRED=n

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
#CONFIG_BT_ATT_TX_COUNT=10

CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y
#CONFIG_PROSPECTOR_STATUS_SCREEN_FIELD=y
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
#CONFIG_LV_Z_VDB_SIZE=25