CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_KEYBOARD_NAME="Sweep"

CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=0
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
#CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y

# disable BLE on peripheral
# NOTE: keep default (=y) if want to pairing BLE host on split central, or wireless dongle
CONFIG_ZMK_BLE=n

# disable default split transport on central and peripheral
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED=n

# enable split esb transport
CONFIG_ZMK_SPLIT_ESB=y

# enable ESB TX send request packet payload with ACK bit
# ESB protocol has built-in retransmit counter (default one), if RX does not response ACK properly.
# disable this iif you are pursuing extreme low latency, not much different in real-life.
CONFIG_ZMK_SPLIT_ESB_PROTO_TX_ACK=y

# The delay between each retransmission of unacknowledged packets
# NOTE: radio will chock if too short
CONFIG_ZMK_SPLIT_ESB_PROTO_TX_RETRANSMIT_DELAY=500

# The number of retransmission attempts before transmission fail
# NOTE: applying less retransmit count on pointer device will lead to lossy but sharper move
CONFIG_ZMK_SPLIT_ESB_PROTO_TX_RETRANSMIT_COUNT=3

# The number of Multi-Protocol Service Layer (MPSL) timeslot sessions
# set 1, if CONFIG_ZMK_BLE is disabled on central or peripherals
# set 2, if CONFIG_ZMK_BLE is enabled on central, which needs BLE and ESB simultaneously
CONFIG_MPSL_TIMESLOT_SESSION_COUNT=1

# Number of message queue size to buffer ESB payload for TX in between multi-protocol service 
# timeslots (CONFIG_MPSL_TIMESLOT_SESSION_COUNT)
CONFIG_ZMK_SPLIT_ESB_PROTO_MSGQ_ITEMS=16

# qeuue size for both peripheral (EVENT) and central (CMD)
CONFIG_ZMK_SPLIT_ESB_EVENT_BUFFER_ITEMS=16
CONFIG_ZMK_SPLIT_ESB_CMD_BUFFER_ITEMS=4

# another IMPORTANT config for ESB
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_ESB_MAX_PAYLOAD_LENGTH=48

# currently, set ESB_TX_FIFO to 1, to workaround ACK issues before NCS 3.1.0 release
# NOTE: should apply to both TX and RX sides
CONFIG_ESB_TX_FIFO_SIZE=1

# Logging!
# CONFIG_ZMK_SPLIT_ESB_LOG_LEVEL_DBG=y

# for battery reporting on RX
# NOTE: CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS is valid for ESB-only, even its look like a BLE-only config.
# NOTE: central will not advertise to any BLE host if ble_profile_count is zero.
#       with simple math:
#       ZMK_BLE_PROFILE_COUNT = (CONFIG_BT_MAX_PAIRED - CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS)
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_BT_MAX_PAIRED=2
CONFIG_DONGLE_SCREEN_BATTERY_ACTIVE=n
CONFIG_DONGLE_SCREEN_OUTPUT_ACTIVE=n